-- AlterTable
ALTER TABLE `Material` MODIFY `talhao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `product` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `classification` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `Operation` MODIFY `service` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `culture` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `areaMap` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `equipment` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `model` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `TechReport` MODIFY `date` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `init` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `finish` VARCHAR(191) NOT NULL DEFAULT '';
